title: Chenxi Huang's Homepage
page-top-title: Chenxi Huang
top-section-bg-text: Social Sciennce
home-subtitle: Chenxi Huang&ensp;|&ensp;黄晨熙
copyright-text: '&copy; Chenxi Huang 2023-2025. All Rights Reserved.'
